site_name: Documentation du servive - SISEP
# site_name: SISEP DOC
repo_url: https://github.com/JRII972/Documents-SISEP
theme:
  name: material
  locale: fr
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections 
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share

plugins:
  # - meta
  - table-reader
  - search:
      lang: fr
      # prebuild_index: true
      # indexing: 'full'
  - tags:
      tags_file: tags.md
  - mkdocs-jupyter
  - categories:
      generate_index: true
      verbose: false
      base_name: 'categorie'
      section_title: 'Catégories'
      no_nav: false
      # category_separator: '|' # TODO: search good settings

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - js/mathjax.js
  - js/polyfill.min.js?features=es6
  - js/tex-mml-chtml.js